language: node_js

os: linux

dist: xenial

branches:
  except:
    - docs

cache:
  npm: true
  directories:
    - ~/.cache

stages:
  - unit test
  - integration test
  - name: acceptance test
    if: branch IN (master, dev)
  - name: staging build
    if: (
      branch = dev
      AND
      type = push
      )
  - name: deploy
    if: (
      branch = master
      AND
      type = push
      )

jobs:
  include:
    # For base alias
    - &node_12_backend_base
      stage: unit test
      node_js: 12
      os: linux
      install:
        - cd backend;
          npm install;
      env:
        - secure: "jTkfY40vQnnT01n5qrQykEjH5Iyqjik3ucVKDypVVUnJO0u+B8ChfM5wfpAcoerzP7SLUGUM0lVJwTjKUE1zxR3vA/62CCJVAp+F/YoiHvEhBHJ0WTriY+Bo//Pw4RtfKerWj4kMWl9EQF12zQdsMq2XbNDV8rLmRw6trgeTzRANHFevFGvaoYcKgP4AENDZciVGH70eWzEyBqRqu4WmOQ69OQQSbgUu6wHcvMAwQEizPg6vw9SGWoHXPgXYsymWf/G0VtogY3K/iuaou9RISlAI3MlcgdsJ4pzHWGDAyclxRTEsdg/1nkFqgpp2lzrUTkdh6yhwsEKsCdueAldQRo/SOodqydjISWuW0CDX60i2+te4urrV283veJxiOlMe6tledvOihMU+NEqyz8ORPXmKf7dkruoCwLEjqBowHGKkqsPCECpuvghb4mgs/FEtNiOOsBTeXv3quo8pBqySyiEWOG2sT9apsdf9mC7xxTM62bTIS/zpFKsszGnjfhJOu3aqiPq75ZZaYbb3T4fu8IJnCee7MeG8+IwDdKh7lNQ/iqRoP6Vp3KWWXb2jwERRgCb393Kwpfkj27IbOM6dy5ToiY3uYMPaluZIsUEWHuvlF+6W32Iq3RyfJsuIH94du2EOQdEfQPuQtdCy7BwqCuo2ToXLtEOjqDOfTwCqWLs="
        - NODE_ENV=UNIT_TEST
      script:
        - npm run unit

    # Int test
    - <<: *node_12_backend_base
      stage: integration test
      env:
        - secure: "jTkfY40vQnnT01n5qrQykEjH5Iyqjik3ucVKDypVVUnJO0u+B8ChfM5wfpAcoerzP7SLUGUM0lVJwTjKUE1zxR3vA/62CCJVAp+F/YoiHvEhBHJ0WTriY+Bo//Pw4RtfKerWj4kMWl9EQF12zQdsMq2XbNDV8rLmRw6trgeTzRANHFevFGvaoYcKgP4AENDZciVGH70eWzEyBqRqu4WmOQ69OQQSbgUu6wHcvMAwQEizPg6vw9SGWoHXPgXYsymWf/G0VtogY3K/iuaou9RISlAI3MlcgdsJ4pzHWGDAyclxRTEsdg/1nkFqgpp2lzrUTkdh6yhwsEKsCdueAldQRo/SOodqydjISWuW0CDX60i2+te4urrV283veJxiOlMe6tledvOihMU+NEqyz8ORPXmKf7dkruoCwLEjqBowHGKkqsPCECpuvghb4mgs/FEtNiOOsBTeXv3quo8pBqySyiEWOG2sT9apsdf9mC7xxTM62bTIS/zpFKsszGnjfhJOu3aqiPq75ZZaYbb3T4fu8IJnCee7MeG8+IwDdKh7lNQ/iqRoP6Vp3KWWXb2jwERRgCb393Kwpfkj27IbOM6dy5ToiY3uYMPaluZIsUEWHuvlF+6W32Iq3RyfJsuIH94du2EOQdEfQPuQtdCy7BwqCuo2ToXLtEOjqDOfTwCqWLs="
        - NODE_ENV=INT_TEST
      script:
        - npm run int
    
    - &node_12_frontend_base
      stage: integration test
      node_js: 12
      os: linux
      install:
        - cd frontend;
          npm install
      before_script:
        - npx http-server files -c-1 &
      script:
        - npm run cy_int_test

    # Acceptance test
    - stage: acceptance test
      node_js: 12
      os: linux
      env:
        - secure: "iO3rM6KNRoKT9uEG//ck1qCP9qh+R0aCsJVH5I9GGagy8JQr2oBFmbnYAtZ/CD2F+ez23hm1erXe0m6FhyY6Us4sMM6w5GinfwYlpsUck+LGydUq67mhA+wZQdCY+T3ULUENrkfZMoSEq/z3oSw2mafbrBr9JNVn2M0ghCfEK9c9ZrlTbXEIwj77KIdU9i1rdxrWwZF9wY0rLt40noUyl/d2XJyXlo8mN6yAAMz5aYhcuLL2OPhNtVueP4hoWXlPLpixy89xBMc/U6+Jxw5PbOwviyWt/VbVtw3r1pUTi+0KLdIUpfhcZgQMvikQnPSGZDCg6KFvkwMurPy/jbb4sU2LhAm1gwr5XVjXyWm2axPHtyuUvN/vw/gFV4qVp1z4zgHO5N/q4A9zzwQ/MOtA2dshltW5atOq/giQ/UZvRJyYlih+KP4qQQUZ1FjIq5DoLH6P3gcAY2zqSWvmJiQ+pGqjVPaiGcDdzwMTY95YPlXmMHpYQr2pSWJ6LSGDFgGg75P4udQt8v3Pr2VF1OBcfdeXdX6jVz4MQukhzYEcpJzfPXEzjA/LTpfQHIajPGNT7QxtPAr5hmKoBla7VR4H6VY3rbjenWOIRyzbrzENpJcjB/jRPtvOkKDprtg8xkdOwrPtdhpKcpdv2YvLejcw2cms8hPNLgdvVScvbimgVgg="
        - NODE_ENV=ACC_TEST
      install:
        - cd backend;
          npm install;
          cd ..;
          cd frontend;
          npm install;
      before_script:
        - sed -i -e 's/false/true/' files/configs.js;
        - npx http-server files -c-1 &
        - cd ..; cd backend; npm start &
        - cd ..; cd frontend
      script:
        - npm run cy_acc_test
    
    # Staging
    - stage: staging build
      script: skip
      before_deploy: cd backend
      deploy:
        provider: heroku
        api_key:
          secure: ORrM1Ksm3AhExca2fbFbl5McHbRJQ/Pqlw+5wUherBjVD+sgggtRnjUcqxRhgWszhftXMjdw3YaNB5u7FaDlDca1SFrvAndn1/vpuDjjzmG97S71gFX+Muzd6Y48npab4t1S5vMXn/QB+RE0Xcg3Vz6FisasQ9RqP5mWK/LtDhs6O6XPH7zgWEsAiQs5UpnEA8a4Hnh/n685o7C7W1f3E+LqxYP4UgtobFg/5Ktut9gY5ibp3J+7R0kr9DHe4gwjlAJYCKLNrAT2qS1CV10vp0EFaH8dCMwRFNnHJkJULeVWk/Mb6SUBCqw7rDIBZkjF2ADTLk8NV7o0T5g7DBE5CtMT54W/R0uRQWm0nLQDIREidvy3ugxDUj4lA4yRgRiJO+csgGwE9pob9jqL+8Z9yS8RIPLSi76BzZZflWleQusWLdJu6Lju1Q/KGH1tGJ7lGPrS+1vPWQYorhKmldy21yBvG/EJySkVlT6h6O5jBzY+Zq5mmnkz6Pl22hx+MiQ84HjTMRpVBHw2vPy+26cDSqR9gjf8iklCwdAhAP0ugOZdWkdNE3gnB2RROrQOnmDOLREF5f9e2/GdLzuhmEzrae5h+6Imtj16VRaadI6YUHO3ksa1jIusJgREjzPztyjfA/GEvs4muscao/FAP2nvYHvW0ZS3D3DXD5O/YVqWfE4=
        app: fsp-staging
        on: dev

    # Deployment stage
    - stage: deploy
      script: skip
      before_deploy: cd backend
      deploy:
        provider: heroku
        api_key:
          secure: ORrM1Ksm3AhExca2fbFbl5McHbRJQ/Pqlw+5wUherBjVD+sgggtRnjUcqxRhgWszhftXMjdw3YaNB5u7FaDlDca1SFrvAndn1/vpuDjjzmG97S71gFX+Muzd6Y48npab4t1S5vMXn/QB+RE0Xcg3Vz6FisasQ9RqP5mWK/LtDhs6O6XPH7zgWEsAiQs5UpnEA8a4Hnh/n685o7C7W1f3E+LqxYP4UgtobFg/5Ktut9gY5ibp3J+7R0kr9DHe4gwjlAJYCKLNrAT2qS1CV10vp0EFaH8dCMwRFNnHJkJULeVWk/Mb6SUBCqw7rDIBZkjF2ADTLk8NV7o0T5g7DBE5CtMT54W/R0uRQWm0nLQDIREidvy3ugxDUj4lA4yRgRiJO+csgGwE9pob9jqL+8Z9yS8RIPLSi76BzZZflWleQusWLdJu6Lju1Q/KGH1tGJ7lGPrS+1vPWQYorhKmldy21yBvG/EJySkVlT6h6O5jBzY+Zq5mmnkz6Pl22hx+MiQ84HjTMRpVBHw2vPy+26cDSqR9gjf8iklCwdAhAP0ugOZdWkdNE3gnB2RROrQOnmDOLREF5f9e2/GdLzuhmEzrae5h+6Imtj16VRaadI6YUHO3ksa1jIusJgREjzPztyjfA/GEvs4muscao/FAP2nvYHvW0ZS3D3DXD5O/YVqWfE4=
        app: fsp-deploy
        on: master

    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token:
          - secure: "dFelDLQFUHzchISUvUK9LSMoomS8b9hKvjRj8+6/cyfNTnNtg7SRdlxzc/1Eh2WBe7uvPkgh8ljDcY0dtn46YsgieTFV4iAH4W/QcIMTQitqC0Fe+V1XUT+T9plFRtW0uiu53aLhFl4Ryt1v62hOx+3rojq4l2ZZi5Xm+UoxDSmTTrhNBSlgpZ4nFsqCl+wjnbPDRbUxpgmRHNh3u0xt7fCIeyh/ePDtLxolrgFR+aigiSdnzKYa6nG2U5oj+VEKeB2LiE8oDqlVqDf1NoK839q5w8kxbYbzRka81Z95JJrQcgE394/gDPGrXdrMw0IK559Vct2BIcwyIRQael3ev6UUiOAh50+SOD6yV+3bO8RuzgyapRm3NUxSI+LcrUnAW917r9lPZ3vw6EykFuig3y7Q4i4Z72b0YGwKBZE6dSVv0U/tdqpY+ejH5ouSOXJS1pseyEeSudI4MG2te25sbwQq3eajdWD36DWO3yrtXG3hOb94tYkhLHJaYcX8zL6P2zcsFmsDqdiEvMPSnL2yxEEq3U+NPwnhUUJUv1E/77koAMHPzawZ7Alhe5SNy23vnDpB+4+ibqil4shR4XT9rLu7SLxzYkmtml7gy6stCRxtvwAg2g6zR2viWTuUlRBd/m84P0JeVHTaTudE9RWeksk5dbmkLEbOyT04B+yxLpQ="
        keep_history: true
        local_dir: frontend/files
        target_branch: gh-pages
        on:
          branch: master