language: node_js

os: linux

dist: xenial

branches:
  except:
    - docs

cache:
  npm: true
  directories:
    - ~/.cache

stages:
  - unit test
  - integration test
  - name: acceptance test
    if: branch IN (master, dev)
  - name: staging build
    if: (
      branch = dev
      AND
      type = push
      )
  - name: deploy
    if: (
      branch = master
      AND
      type = push
      )

jobs:
  include:
    # For base alias
    - &node_12_backend_base
      stage: unit test
      node_js: 12
      os: linux
      install:
        - cd backend;
          npm install;
      env:
        - secure: CkIREEp2Dob11f1E4P92l7JDSZgNbSmxkVY50neUoGVA6C3wpujjbpEJzGemiX5dx5VL8SlUSmcI+svP4a/mDDYPur4VmcEhosd9O/qoug2TJGTj4IhowFV1qSOTaDbx/HYmo5KuLAnxsNGhI6lZO4xTYTVxiPeBFuzzLxsAXz5TvUgajwZmO5IqduTAtbLBtCaK0BoDlk/NiTJS9PvHMBjLNmmVouGp9ae6fUxEdGdz5VwlCv3iKKiFE5YLEGenUES8zYXd5qGIToDX19HNDvs83/KauR65IgfC5SCrK3FoFBDDx9Rhqldiym372OaE5c8SHhqEErEqVpDyx7Xnzpgr2ktz3pL1NcIG30cZdEpSindzEf4IPZA14Ob3WapdGex1LdPVxA44asJqpAFyabSOIWNSPAzgp9mlCoM/a6NFrvRJXsGeLDtcB6bLNfOrZ5zFhovsvjz9ZQswSxg69b4Pnw+WgfOvwmTkQEsvOOk7k/Hi21ZAZAJpwFGUBTSpCIU/zu2hoBj0Cw4VqMVDbRoqibkGvrdtcbVHrYdOtB+oskZ6Q2l/nteS9rdRewpq/hpOJuU1tYSXiw9Xo8MIkEXW0zba8OuI3Zc8IyIOaBxZPadl2LrdFlaxhpQB45TlYAPVCJ+wcv/EUWbwNtd1MNhWWWlvD78qgVjV7J+8w2Y=
        - NODE_ENV=UNIT_TEST
      script:
        - npm run unit

    # Int test
    - <<: *node_12_backend_base
      stage: integration test
      env:
        - secure: "CkIREEp2Dob11f1E4P92l7JDSZgNbSmxkVY50neUoGVA6C3wpujjbpEJzGemiX5dx5VL8SlUSmcI+svP4a/mDDYPur4VmcEhosd9O/qoug2TJGTj4IhowFV1qSOTaDbx/HYmo5KuLAnxsNGhI6lZO4xTYTVxiPeBFuzzLxsAXz5TvUgajwZmO5IqduTAtbLBtCaK0BoDlk/NiTJS9PvHMBjLNmmVouGp9ae6fUxEdGdz5VwlCv3iKKiFE5YLEGenUES8zYXd5qGIToDX19HNDvs83/KauR65IgfC5SCrK3FoFBDDx9Rhqldiym372OaE5c8SHhqEErEqVpDyx7Xnzpgr2ktz3pL1NcIG30cZdEpSindzEf4IPZA14Ob3WapdGex1LdPVxA44asJqpAFyabSOIWNSPAzgp9mlCoM/a6NFrvRJXsGeLDtcB6bLNfOrZ5zFhovsvjz9ZQswSxg69b4Pnw+WgfOvwmTkQEsvOOk7k/Hi21ZAZAJpwFGUBTSpCIU/zu2hoBj0Cw4VqMVDbRoqibkGvrdtcbVHrYdOtB+oskZ6Q2l/nteS9rdRewpq/hpOJuU1tYSXiw9Xo8MIkEXW0zba8OuI3Zc8IyIOaBxZPadl2LrdFlaxhpQB45TlYAPVCJ+wcv/EUWbwNtd1MNhWWWlvD78qgVjV7J+8w2Y="
        - NODE_ENV=INT_TEST
      script:
        - echo 'pass int'
    
    - &node_12_frontend_base
      stage: integration test
      node_js: 12
      os: linux
      install:
        - cd frontend;
          npm install
      before_script:
        - npx http-server files -c-1 &
      script:
        - npm run cy_int_test

    # Acceptance test
    - stage: acceptance test
      node_js: 12
      os: linux
      env:
        - secure: "au8+KjFyspis0Q6WzhJqMJkk/zS5h8pY879UIGUrtKwWfLgrJjMLDoAPZcFkZKPcrr51s/UerNUV9pKMn3s0IxGHItBTi1+O1/708njtnDWJqLjAHBd7J4m4NhELqlCJ4VhRo+EaJWZLdenAJUScrhKY28r8ytERwgQ+5iq8Nthpn/t+vyDcfU1i+rEB2kUFroRAZ/PXC8KeCudXlU6yvjgzGCF70+qgLWt8M8yGDv/nQhi48/Mpdzq6LoDMIde2KLYy1B9AHHFkOSNlPYWVfcbqcRs3i4KcVqUxwwYfrcnMzv6kNT1N59FeIsEWiII+sAW/IRTTco2YDDJLtip5qPPs+yU0smDcKYj3v2+3q/Et8GYeuCLfzxUjgC+SV7rKO/skg1ThkHwIS07hVe+i5UdlgeRt7Minza+QpyU/0+OxK1G4ckNd9Etf5b4y+ri/4Mj/xLKYp3oRYJ4jBuNVvtAmc2C+iex60wa3u4+MDvdmgSgN4xXk0eif+WBuHie2Z0vSd5dgD6++jqRnzBe09owxvV60RzB/29k43YZgdOIM67QdsdRof2271vph0DNIBmgw43Uj0Taf/A5A0nQk7QYkKBNGGfl/vT+meaplDs3CFCNsmGdbLfbHwxV93ZCvefAAwkPalAzjbsqzMvlH+sy4ierxETFztrFpH5napQI="
        - NODE_ENV=ACC_TEST
      install:
        - cd backend;
          npm install;
          cd ..;
          cd frontend;
          npm install;
      before_script:
        - sed -i -e 's/false/true/' files/configs.js;
        - npx http-server files -c-1 &
        - cd ..; cd backend; npm start &
        - cd ..; cd frontend
      script:
        - npm run cy_acc_test
    
    # Staging
    - stage: staging build
      script: skip
      before_deploy: cd backend
      deploy:
        provider: heroku
        api_key:
          secure: rznZRW1tiz9PGPnFJufqRtQkgyVuAGUbQCbI70y/fVtxaauPMJmMsmlvOuVI5ejyG2NfUnmN2oe4ecE+em3o856jjqHOxMOgKFuBBYj4Udr6X+c0bRWEzRgg2x39x5EB5tkVdocAzy9f27cyu4o3FgFzgX/leodYSSyfnt6q5kOClCMdo3ehXj38VOFNuQlcn2QOctf4OHb7wumR6y7M94bV6YVyXnwRHiARFqwSpO4RL8K6QZG55AfjP7Qu5kuDYiMWBwRQauldHi6nfq0aJbMYixK1s/jOeyhuuhqBjqlLImnk8muRgmL4IRJC23UO6kaca+QJx9O6l5ExjnssyCnVQ7zyZ3tWyzrf+DPzOnM4+IMuWwP+g5DAdMY9rIHPzSZjLETvP0B0oyJx5dWvZic+Ifmkp3Hmv5P5LpwyNyIhlJx3t1h0lEBw204Qkr7d8AZCNqBaWare8T1FRKODz67SxI3U0NfzBeyUoKnsIASUdll9hKGugNFiYjc0iuolxcvIUyVToPn1X7D7K5HFrxIbAqSQpJC+xmkAsF3if+l5gY8srZ8eiE/oJ566WEG0y1hp+XiicGuI6yzUZJII/449kDvcJQXe+RbUOrc3fz1H2Rd8yMmggtjqF6TYzN2R5UDEwpikyLPRBSec1tPHURk3woM8tARwxdSe9HoNZc4=
        app: fsp-staging
        on: dev

    # Deployment stage
    - stage: deploy
      script: skip
      before_deploy: cd backend
      deploy:
        provider: heroku
        api_key:
          secure: rznZRW1tiz9PGPnFJufqRtQkgyVuAGUbQCbI70y/fVtxaauPMJmMsmlvOuVI5ejyG2NfUnmN2oe4ecE+em3o856jjqHOxMOgKFuBBYj4Udr6X+c0bRWEzRgg2x39x5EB5tkVdocAzy9f27cyu4o3FgFzgX/leodYSSyfnt6q5kOClCMdo3ehXj38VOFNuQlcn2QOctf4OHb7wumR6y7M94bV6YVyXnwRHiARFqwSpO4RL8K6QZG55AfjP7Qu5kuDYiMWBwRQauldHi6nfq0aJbMYixK1s/jOeyhuuhqBjqlLImnk8muRgmL4IRJC23UO6kaca+QJx9O6l5ExjnssyCnVQ7zyZ3tWyzrf+DPzOnM4+IMuWwP+g5DAdMY9rIHPzSZjLETvP0B0oyJx5dWvZic+Ifmkp3Hmv5P5LpwyNyIhlJx3t1h0lEBw204Qkr7d8AZCNqBaWare8T1FRKODz67SxI3U0NfzBeyUoKnsIASUdll9hKGugNFiYjc0iuolxcvIUyVToPn1X7D7K5HFrxIbAqSQpJC+xmkAsF3if+l5gY8srZ8eiE/oJ566WEG0y1hp+XiicGuI6yzUZJII/449kDvcJQXe+RbUOrc3fz1H2Rd8yMmggtjqF6TYzN2R5UDEwpikyLPRBSec1tPHURk3woM8tARwxdSe9HoNZc4=
        app: fsp-deploy
        on: master

    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token:
          - secure: "ykGjdEHIJLLKln2KZbc3SfgQEie8dnTJNUnaC1syaSrALioFcmcybOWTDtljHybOCgeP5wFNKlXzjsNUZlM1B4VtsAX5iO+VAZfdyLqMgwIjD04Jqvq8COqDP+UkTN7d00sEQB2sr50OrxIkUDTYCQZGaIDV0lfu/u08S7dQRIm/P2tR0VwRbIJKc/TbnIqiHgLq+/9g+UJKzKdj4XNtGLpvchpWHHN6WZENN0n8DH7E0RdEt0QwoiGYvaKUoOp2Et95U9WQiGbAMpoqTi9J+ZdQUpJYQNxSVONx1vaUjFdItM6EICixB3c0XH0x6oev0THUxJKtVClN9bkqvcNaBgXBW1BG4POz9BPF7CBhKrguBkBJeSaIYg432M2T45UxyVZBqIgTlwQmqMRbyeDlogXeMoHUpVyPKWUPfkbmyEXh1HGfJ2XyETXOXlBrXqXj1fVQ8En+s/PPin+YI37NCXGSqL5ybGSevbyZn77HiiydLciAwpK4IcMpAJ4Dd9f52QAHZVEyIE38yW0fvNnw7z0+J4e1nUmDhGwIFbDWB8BrZ4S9JVWOsVzN6ImHeDgLjFEJmQnO9rlIzIX3oHdGbV1W14nj9GRiZ6ylLYqZG8XZdgI8KK7NHoSGAQNGpKtGI3Jsf8qkjD2Q4ZB4BTgYejRpaClERt4Pv4SeVwL9GyU="
        keep_history: true
        local_dir: frontend/files
        target_branch: gh-pages
        on:
          branch: master